services:
  storage:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - net

  flyway-migration:
    container_name: db_migration
    image: flyway/flyway:9.22.3-alpine
    command:
      - migrate
      - -url=jdbc:postgresql://storage:5432/${POSTGRES_DB}
      - -user=${POSTGRES_USER}
      - -password=${POSTGRES_PASSWORD}
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - storage
    networks:
      -  net

  app:
    container_name: weather-forecasting-service
    build: .
    environment:
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://storage:5432/${POSTGRES_DB}
    ports:
      - '8080:8080'
    depends_on:
      - flyway-migration
    networks:
      - net
networks:
  net:
    driver: bridge

