services:
  storage:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - net

  flyway-migration:
    container_name: db_migration
    image: flyway/flyway:9.22.3-alpine
    command:
      - migrate
      - -url=jdbc:postgresql://storage:5432/${POSTGRES_DB}
      - -user=${POSTGRES_USER}
      - -password=${POSTGRES_PASSWORD}
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - storage
    networks:
      -  net

  app:
    container_name: weather-forecasting-service
    build: .
    environment:
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://storage:5432/${POSTGRES_DB}
    ports:
      - '8080:8080'
    depends_on:
      - flyway-migration
      - cache
    networks:
      - net
  cache:
      container_name: cache-container
      image: redis:alpine
      ports:
        - "6379:6379"
      environment:
        SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      networks:
        - net
  broker:
    image: redpandadata/redpanda:v23.3.13
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://broker:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://broker:28082,OUTSIDE://localhost:8082
    ports:
      - "9092:9092"
      - "9644:9644"
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    environment:
      SERVER_PORT: ${KAFKA_SERVER_PORT}
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTERS_0_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS}
    depends_on:
      - broker
    ports:
      - "8084:8084"

networks:
  net:
    driver: bridge

