spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  cache:
    type: caffeine
  data:
    redis:
      port: 6379
      host: cache
  kafka:
    bootstrap-servers: broker:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.dto.event"

weather-forecast:
    baseUrl: https://projecteol.ru
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2ODg3MTY3LCJpYXQiOjE3NDY4ODY4NjcsImp0aSI6IjVmNmVjN2JkN2Y3MDRjMzRiZWQ2MmJjYWExOWNlMjRiIiwidXNlcl9pZCI6ODYyfQ.mLNoCP08UCZ-E5gM6hayl5EzqIOsO8xKaBj_yB_QyR4

city-coordinates:
    baseUrl: https://geocode-maps.yandex.ru
    api-key: 46352c14-361b-4a45-99f7-c34e5d78f90d